treeSort code added
kobekovich/sortAlgorithms pull request #2
Opened 2019-11-19 11:43 UTC by kobekovich

Hi Oleksii,

Could you please review the 'tree sort' algorithm?

Thanks

2019-11-24 19:23 UTC, Hopchenko requested changes

2019-11-24 19:23 UTC, Hopchenko commented on BubbleSort/bubbleSort.js
> +function fillInputArray() {
don't repeat yourself, move this function to a separate file and use everywhere you need

2019-11-24 19:23 UTC, Hopchenko commented on BubbleSort/bubbleSort.js
> +let inputArrayLength = 10000;
for such kind of values you can use const

2019-11-24 19:23 UTC, Hopchenko commented on BubbleSort/bubbleSort.js
> +    let multipliers = [-1000,-100,100,1000];
read the difference btw const and let and best practice also

2019-11-24 19:23 UTC, Hopchenko commented on LinearSort/linearSort.js
> +    let startTime = new Date();
you can move time measure logic to a separate function to not repeat the code

2019-11-24 19:23 UTC, Hopchenko commented on LinearSort/linearSort.js
> +
measure function can get measured function as argument

2019-11-24 19:23 UTC, Hopchenko commented on TreeSort/treeSort.js
> +showResult();
good job!

2019-11-28 16:35 UTC, kobekovich commented on BubbleSort/bubbleSort.js
> +function fillInputArray() {
fixed

2019-11-28 16:36 UTC, kobekovich commented on BubbleSort/bubbleSort.js
> +let inputArrayLength = 10000;
changed to const

2019-11-28 16:36 UTC, kobekovich commented on BubbleSort/bubbleSort.js
> +    let multipliers = [-1000,-100,100,1000];
ok

2019-11-28 16:36 UTC, kobekovich commented on LinearSort/linearSort.js
> +    let startTime = new Date();
done

2019-11-28 16:36 UTC, kobekovich commented on LinearSort/linearSort.js
> +
done

2019-11-28 16:37 UTC, kobekovich commented on TreeSort/treeSort.js
> +showResult();
thank you

2020-01-02 14:12 UTC, Hopchenko approved these changes

2020-01-13 14:54 UTC, merged